// Hand-written — aggregates team templates from all four sources into
// TEAM_CATALOG. Three of these files are auto-generated by `pnpm ingest:marketplace`;
// `clawboo-builtin.ts` is hand-written.

import type { TeamTemplate } from '@/features/teams/types'

import { AGENCY_WORKFLOW_TEAMS } from './agency-workflows'
import { AWESOME_OPENCLAW_TEAMS } from './awesome-openclaw'
import { CLAWBOO_BUILTIN_TEAMS } from './clawboo-builtin'
import { SYNTHETIC_EXCELLENCE_TEAMS } from './synthetic'

export { AGENCY_WORKFLOW_TEAMS } from './agency-workflows'
export { AWESOME_OPENCLAW_TEAMS } from './awesome-openclaw'
export { CLAWBOO_BUILTIN_TEAMS } from './clawboo-builtin'
export { SYNTHETIC_EXCELLENCE_TEAMS } from './synthetic'

/** All teams across all sources — clawboo builtins + agency workflows + awesome-openclaw + synthetic. */
export const TEAM_CATALOG: TeamTemplate[] = [
  ...CLAWBOO_BUILTIN_TEAMS,
  ...AGENCY_WORKFLOW_TEAMS,
  ...AWESOME_OPENCLAW_TEAMS,
  ...SYNTHETIC_EXCELLENCE_TEAMS,
]
