#!/usr/bin/env tsx
/**
 * The seed: the one pack that is COMPILED IN rather than fetched.
 *
 * WHY A SEED EXISTS AT ALL. `SelectTeamStep` renders with
 * `allowStartFromScratch={false}`, so an empty catalog is not degraded, it is
 * unrecoverable - first-run onboarding has nothing to click. Everything else
 * about the catalog may be offline, missing, or unreachable; the five builtin
 * teams may not be. So they ship in the binary and the index endpoint merges
 * them unconditionally.
 *
 * WHY IT IS EMITTED TWICE. `apps/web/server` (tsup, Node) and `apps/web/src`
 * (Vite, browser) are separate build targets and an eslint boundary forbids
 * either importing the other. The alternative to two generated files is a new
 * workspace package for one generated constant. Both copies come from this one
 * script, in one pass, from the same bytes, and `--check` fails if either drifts.
 *
 * WHY A JSON STRING AND NOT AN OBJECT LITERAL. The payload is agent prose:
 * markdown with quotes, backslashes and newlines. As a JS object literal it is a
 * file Prettier reflows on every regeneration and a reviewer cannot read. As one
 * string constant it is stable under Prettier (which never splits a string), it
 * diffs as a single line, and V8 parses JSON faster than it parses an equivalent
 * literal. The quote character is chosen the way Prettier chooses it, so a
 * regenerated seed passes `format:check` with no follow-up `--write`.
 *
 * Usage:
 *   tsx scripts/catalog/build-seed.ts            write the generated modules
 *   tsx scripts/catalog/build-seed.ts --check    fail if they are not current
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { agentRow, bundleOf, parseOrThrow, teamRow } from './build-index.ts'
import { REPO_ROOT, loadConfig, loadPack, refEquals } from './lib/packs.ts'

const SPA_DIR = path.join(REPO_ROOT, 'apps/web/src/features/marketplace/seed')
const SPA_DATA = path.join(SPA_DIR, 'packs.ts')
const SPA_BARREL = path.join(SPA_DIR, 'index.ts')
const SERVER_FILE = path.join(REPO_ROOT, 'apps/web/server/lib/catalogSeed.ts')

const BANNER = [
  '// GENERATED by scripts/catalog/build-seed.ts from catalog/packs/clawboo/builtin.',
  '// Do not edit by hand: `pnpm catalog:verify` fails when this file and the pack',
  '// disagree. Change the pack, then run `pnpm catalog:build`.',
].join('\n')

/**
 * Prettier's own quote choice: the character that needs fewer escapes, single on
 * a tie. Same rule the retired allowlist generator used, and the reason a
 * regenerated file does not fail `format:check`.
 */
function quoted(value: string): string {
  const singles = (value.match(/'/g) ?? []).length
  const doubles = (value.match(/"/g) ?? []).length
  const quote = singles > doubles ? '"' : "'"
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(new RegExp(quote, 'g'), `\\${quote}`)
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
  return `${quote}${escaped}${quote}`
}

function spaModule(raw: string): string {
  return `${BANNER}
//
// The offline half of the marketplace. Everything else is fetched from
// \`/api/catalog/*\`; this is what renders when that fetch cannot be made.

import type { AgentBody, CatalogIndex, TeamBody } from '../catalogTypes'

interface SeedPayload {
  index: CatalogIndex
  agentBodies: Record<string, AgentBody>
  teamBodies: Record<string, TeamBody>
}

const RAW =
  ${quoted(raw)}

const payload = JSON.parse(RAW) as SeedPayload

/** Browse rows for the builtin pack. Always available, never fetched. */
export const SEED_INDEX: CatalogIndex = payload.index

export const SEED_AGENT_BODIES: Record<string, AgentBody> = payload.agentBodies

export const SEED_TEAM_BODIES: Record<string, TeamBody> = payload.teamBodies
`
}

function spaBarrel(packId: string, version: string): string {
  return `${BANNER}
//
// The seam. App code imports the seed from here, never from './packs' directly,
// so the generated data module has exactly one consumer.

export { SEED_AGENT_BODIES, SEED_INDEX, SEED_TEAM_BODIES } from './packs'

/** The pack the seed was cut from. */
export const SEED_PACK_ID = '${packId}'
export const SEED_PACK_VERSION = '${version}'
`
}

function serverModule(raw: string, packId: string, version: string): string {
  return `${BANNER}
//
// The server's copy. \`apps/web/server\` and \`apps/web/src\` are separate build
// targets and an eslint boundary forbids either importing the other, so the
// shapes below are declared locally rather than imported from the SPA. They are
// the same bytes: one generator, one pass, and \`pnpm catalog:verify\` fails if
// the two copies ever disagree.

export interface SeedAgentRow {
  id: string
  packId: string
  name: string
  role: string
  emoji: string
  color: string
  description: string
  source: string
  category: string
  tags: string[]
  skillIds: string[]
  suggestedRuntime?: string
}

export interface SeedTeamRow {
  id: string
  packId: string
  name: string
  emoji: string
  color: string
  description: string
  category: string
  source: string
  tags: string[]
  agentIds: string[]
  defaultRuntime?: string
}

export interface SeedIndex {
  schemaVersion: number
  counts: { agents: number; teams: number }
  agents: SeedAgentRow[]
  teams: SeedTeamRow[]
}

export interface SeedAgentBody {
  id: string
  files: Record<string, string>
  sourceUrl?: string
}

export interface SeedTeamBody {
  id: string
  workflowNarrative?: string
  routing?: Record<string, string>
  sourceUrl?: string
}

interface SeedPayload {
  index: SeedIndex
  agentBodies: Record<string, SeedAgentBody>
  teamBodies: Record<string, SeedTeamBody>
}

const RAW =
  ${quoted(raw)}

const payload = JSON.parse(RAW) as SeedPayload

export const SEED_INDEX: SeedIndex = payload.index
export const SEED_AGENT_BODIES: Record<string, SeedAgentBody> = payload.agentBodies
export const SEED_TEAM_BODIES: Record<string, SeedTeamBody> = payload.teamBodies

/** The pack the seed was cut from. */
export const SEED_PACK_ID = '${packId}'
export const SEED_PACK_VERSION = '${version}'
`
}

export function buildSeed(): { files: { file: string; text: string }[]; bytes: number } {
  const config = loadConfig()
  const ref = config.packs.find((p) => refEquals(p, config.seed))
  if (!ref) {
    throw new Error(
      `catalog.config.json names a seed pack (${config.seed.publisher}/${config.seed.slug}) ` +
        'that is not in its own packs list.',
    )
  }
  const loaded = loadPack(ref)
  const pack = parseOrThrow(loaded)
  const bundle = bundleOf(loaded, pack)

  // `origin.url` lives on the LISTING in a pack (one attribution field per
  // entry, next to the rest of the entry's metadata) but the detail sheets read
  // it off the BODY they already fetched. Flattening it here keeps the served
  // shape and the compiled shape identical, so the fallback is a drop-in.
  // `apps/web/server/api/catalog.ts` does the same flattening for fetched packs.
  const payload = {
    index: {
      schemaVersion: 1,
      counts: { agents: pack.agents.length, teams: pack.teams.length },
      agents: pack.agents.map((a) => agentRow(pack, a)),
      teams: pack.teams.map((t) => teamRow(pack, t)),
    },
    agentBodies: Object.fromEntries(
      pack.agents.map((a) => [
        a.id,
        { ...bundle.bodies.agents[a.id], ...(a.origin?.url ? { sourceUrl: a.origin.url } : {}) },
      ]),
    ),
    teamBodies: Object.fromEntries(
      pack.teams.map((t) => [
        t.id,
        { ...bundle.bodies.teams[t.id], ...(t.origin?.url ? { sourceUrl: t.origin.url } : {}) },
      ]),
    ),
  }
  const raw = JSON.stringify(payload)

  return {
    files: [
      { file: SPA_DATA, text: spaModule(raw) },
      { file: SPA_BARREL, text: spaBarrel(pack.id, pack.version) },
      { file: SERVER_FILE, text: serverModule(raw, pack.id, pack.version) },
    ],
    bytes: Buffer.byteLength(raw, 'utf8'),
  }
}

function main(): void {
  const check = process.argv.includes('--check')
  const { files, bytes } = buildSeed()

  if (check) {
    const stale = files
      .filter(({ file, text }) => (existsSync(file) ? readFileSync(file, 'utf8') : null) !== text)
      .map(({ file }) => path.relative(REPO_ROOT, file))
    if (stale.length > 0) {
      console.error(
        `catalog: the generated seed is stale:\n${stale.map((f) => `  ${f}`).join('\n')}\n\n` +
          'Run `pnpm catalog:build` and commit the result.',
      )
      process.exit(1)
    }
    console.log(`catalog: seed is current (${(bytes / 1024).toFixed(1)} KB payload)`)
    return
  }

  for (const { file, text } of files) {
    mkdirSync(path.dirname(file), { recursive: true })
    writeFileSync(file, text, 'utf8')
  }
  console.log(
    `catalog: seed ${(bytes / 1024).toFixed(1)} KB -> ` +
      files.map(({ file }) => path.relative(REPO_ROOT, file)).join(', '),
  )
}

if (process.argv[1] && path.resolve(process.argv[1]).endsWith('build-seed.ts')) main()
