// GENERATED by scripts/catalog/build-seed.ts from catalog/packs/clawboo/builtin.
// Do not edit by hand: `pnpm catalog:verify` fails when this file and the pack
// disagree. Change the pack, then run `pnpm catalog:build`.
//
// The seam. App code imports the seed from here, never from './packs' directly,
// so the generated data module has exactly one consumer.

export { SEED_AGENT_BODIES, SEED_INDEX, SEED_TEAM_BODIES } from './packs'

/** The pack the seed was cut from. */
export const SEED_PACK_ID = 'clawboo'
export const SEED_PACK_VERSION = '1.0.0'
