/**
 * Curated emoji catalog for the team-icon picker. Intentionally a hand-picked
 * subset (not the full Unicode set) so there's NO dependency and the grid stays
 * fast and team-relevant. Each entry has a space-separated `n` (name/keywords)
 * so `searchEmojis` can match on any word. Users can still paste any emoji via
 * the picker's "custom" field for anything not listed here.
 */

export interface EmojiEntry {
  /** The emoji character (may be a multi-codepoint ZWJ sequence). */
  c: string
  /** Space-separated search keywords, lowercase. */
  n: string
}

export interface EmojiCategory {
  id: string
  label: string
  emojis: EmojiEntry[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    emojis: [
      { c: '😀', n: 'grinning happy smile' },
      { c: '😄', n: 'happy smile joy' },
      { c: '😁', n: 'grin beam' },
      { c: '😂', n: 'joy laugh lol cry' },
      { c: '🤣', n: 'rofl rolling laugh' },
      { c: '😊', n: 'blush smile happy' },
      { c: '🙂', n: 'slight smile' },
      { c: '😉', n: 'wink' },
      { c: '😍', n: 'heart eyes love' },
      { c: '🥰', n: 'love hearts adore' },
      { c: '😎', n: 'cool sunglasses' },
      { c: '🤩', n: 'star struck wow' },
      { c: '🥳', n: 'party celebrate hat' },
      { c: '🤔', n: 'thinking hmm' },
      { c: '🧐', n: 'monocle inspect curious' },
      { c: '🤓', n: 'nerd geek smart' },
      { c: '😴', n: 'sleeping zzz tired' },
      { c: '🤯', n: 'mind blown exploding' },
      { c: '🥵', n: 'hot heat' },
      { c: '🥶', n: 'cold freeze' },
      { c: '😱', n: 'scream shock fear' },
      { c: '🤗', n: 'hug care' },
      { c: '🤫', n: 'quiet shh secret' },
      { c: '😇', n: 'angel halo innocent' },
      { c: '🤠', n: 'cowboy hat' },
      { c: '🥺', n: 'pleading puppy eyes' },
      { c: '😈', n: 'devil mischief evil' },
      { c: '👻', n: 'ghost boo spooky' },
      { c: '💀', n: 'skull dead bones' },
      { c: '👽', n: 'alien ufo extraterrestrial' },
      { c: '🤖', n: 'robot bot ai machine' },
      { c: '🎃', n: 'pumpkin halloween' },
      { c: '🙈', n: 'see no evil monkey' },
    ],
  },
  {
    id: 'people',
    label: 'People',
    emojis: [
      { c: '🧑‍💻', n: 'developer coder programmer tech' },
      { c: '👩‍💻', n: 'woman developer coder' },
      { c: '👨‍💻', n: 'man developer coder' },
      { c: '🦸', n: 'hero superhero super' },
      { c: '🦹', n: 'villain supervillain' },
      { c: '🧙', n: 'wizard mage magic' },
      { c: '🧚', n: 'fairy magic' },
      { c: '🧛', n: 'vampire' },
      { c: '🕵️', n: 'detective spy investigate' },
      { c: '👷', n: 'builder worker construction' },
      { c: '🧑‍🔬', n: 'scientist research lab' },
      { c: '🧑‍🎨', n: 'artist designer paint' },
      { c: '🧑‍🚀', n: 'astronaut space explorer' },
      { c: '🧑‍🏫', n: 'teacher educator' },
      { c: '🧑‍⚕️', n: 'doctor medic health' },
      { c: '🧑‍🍳', n: 'chef cook kitchen' },
      { c: '🤝', n: 'handshake deal partner agree' },
      { c: '🙌', n: 'celebrate raise hands praise' },
      { c: '👏', n: 'clap applause' },
      { c: '💪', n: 'strong muscle power flex' },
      { c: '🫡', n: 'salute respect' },
      { c: '👀', n: 'eyes look watch' },
      { c: '🧠', n: 'brain smart mind think' },
      { c: '👑', n: 'crown king queen leader royal' },
    ],
  },
  {
    id: 'animals',
    label: 'Animals',
    emojis: [
      { c: '🐶', n: 'dog puppy' },
      { c: '🐱', n: 'cat kitten' },
      { c: '🦊', n: 'fox' },
      { c: '🦁', n: 'lion' },
      { c: '🐯', n: 'tiger' },
      { c: '🐻', n: 'bear' },
      { c: '🐼', n: 'panda' },
      { c: '🐨', n: 'koala' },
      { c: '🐸', n: 'frog' },
      { c: '🐵', n: 'monkey' },
      { c: '🦄', n: 'unicorn magic' },
      { c: '🐲', n: 'dragon' },
      { c: '🦖', n: 'dino dinosaur trex rex' },
      { c: '🐙', n: 'octopus' },
      { c: '🦈', n: 'shark' },
      { c: '🐬', n: 'dolphin' },
      { c: '🐳', n: 'whale' },
      { c: '🦅', n: 'eagle bird' },
      { c: '🦉', n: 'owl wise' },
      { c: '🦋', n: 'butterfly' },
      { c: '🐝', n: 'bee buzz' },
      { c: '🐞', n: 'ladybug bug' },
      { c: '🦜', n: 'parrot bird' },
      { c: '🦦', n: 'otter' },
      { c: '🦥', n: 'sloth slow' },
      { c: '🐢', n: 'turtle tortoise' },
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    emojis: [
      { c: '🌳', n: 'tree' },
      { c: '🌲', n: 'evergreen tree pine' },
      { c: '🌵', n: 'cactus' },
      { c: '🌴', n: 'palm tree tropical' },
      { c: '🌸', n: 'blossom flower cherry' },
      { c: '🌻', n: 'sunflower' },
      { c: '🌹', n: 'rose flower' },
      { c: '🍀', n: 'clover luck four leaf' },
      { c: '🍁', n: 'maple leaf autumn' },
      { c: '🌍', n: 'earth globe world planet' },
      { c: '🌙', n: 'moon night crescent' },
      { c: '⭐', n: 'star' },
      { c: '🌟', n: 'glowing star shine' },
      { c: '✨', n: 'sparkles shine magic new' },
      { c: '⚡', n: 'lightning bolt fast energy' },
      { c: '🔥', n: 'fire flame hot lit' },
      { c: '💧', n: 'water drop droplet' },
      { c: '🌈', n: 'rainbow colorful pride' },
      { c: '❄️', n: 'snowflake cold winter' },
      { c: '🌊', n: 'wave ocean sea water' },
      { c: '☀️', n: 'sun sunny bright' },
      { c: '🌪️', n: 'tornado storm wind' },
      { c: '🌋', n: 'volcano eruption' },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    emojis: [
      { c: '🍕', n: 'pizza' },
      { c: '🍔', n: 'burger hamburger' },
      { c: '🍟', n: 'fries chips' },
      { c: '🌮', n: 'taco mexican' },
      { c: '🍣', n: 'sushi' },
      { c: '🍜', n: 'ramen noodles soup' },
      { c: '🍩', n: 'donut doughnut' },
      { c: '🍪', n: 'cookie biscuit' },
      { c: '🎂', n: 'cake birthday' },
      { c: '🍫', n: 'chocolate' },
      { c: '🍿', n: 'popcorn movie' },
      { c: '☕', n: 'coffee cafe latte' },
      { c: '🍵', n: 'tea matcha' },
      { c: '🧋', n: 'boba bubble tea milk' },
      { c: '🍺', n: 'beer pint' },
      { c: '🥑', n: 'avocado' },
      { c: '🍎', n: 'apple fruit' },
      { c: '🍓', n: 'strawberry berry' },
      { c: '🌶️', n: 'pepper spicy chili hot' },
    ],
  },
  {
    id: 'activity',
    label: 'Activity',
    emojis: [
      { c: '🚀', n: 'rocket launch startup space ship fast' },
      { c: '🛸', n: 'ufo flying saucer' },
      { c: '⚽', n: 'soccer football ball' },
      { c: '🏀', n: 'basketball' },
      { c: '🏈', n: 'football american' },
      { c: '🎾', n: 'tennis' },
      { c: '🏆', n: 'trophy win champion award' },
      { c: '🥇', n: 'gold medal first win' },
      { c: '🎯', n: 'target goal dart bullseye aim' },
      { c: '🎮', n: 'game controller gaming play' },
      { c: '🕹️', n: 'joystick arcade game' },
      { c: '🎲', n: 'dice game random' },
      { c: '🧩', n: 'puzzle piece solve' },
      { c: '🎨', n: 'art palette paint design' },
      { c: '🎭', n: 'theater drama masks' },
      { c: '🎬', n: 'movie film clapper video' },
      { c: '🎸', n: 'guitar music rock' },
      { c: '🎹', n: 'piano keys music' },
      { c: '🎤', n: 'mic microphone sing' },
      { c: '🎧', n: 'headphones music audio' },
      { c: '🥁', n: 'drum beat music' },
      { c: '♟️', n: 'chess strategy pawn' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    emojis: [
      { c: '✈️', n: 'plane travel flight airplane' },
      { c: '🚗', n: 'car auto vehicle' },
      { c: '🏎️', n: 'race car fast speed' },
      { c: '🚲', n: 'bike bicycle cycle' },
      { c: '🚂', n: 'train locomotive' },
      { c: '🚢', n: 'ship boat cruise' },
      { c: '⛵', n: 'sailboat sailing' },
      { c: '🚁', n: 'helicopter chopper' },
      { c: '🛰️', n: 'satellite space signal' },
      { c: '🏠', n: 'house home' },
      { c: '🏢', n: 'office building company work' },
      { c: '🏰', n: 'castle fortress' },
      { c: '🗼', n: 'tower landmark' },
      { c: '🏔️', n: 'mountain peak summit' },
      { c: '🏖️', n: 'beach vacation' },
      { c: '🗺️', n: 'map world explore' },
      { c: '🧭', n: 'compass direction navigate' },
      { c: '🚩', n: 'flag marker milestone' },
      { c: '🏁', n: 'finish flag race checkered' },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    emojis: [
      { c: '💻', n: 'laptop computer code dev' },
      { c: '🖥️', n: 'desktop monitor computer screen' },
      { c: '📱', n: 'phone mobile smartphone' },
      { c: '⌨️', n: 'keyboard type' },
      { c: '💾', n: 'save disk floppy data' },
      { c: '📦', n: 'package box ship product' },
      { c: '🗂️', n: 'folders files organize' },
      { c: '📊', n: 'bar chart data analytics stats' },
      { c: '📈', n: 'chart up growth trend increase' },
      { c: '📉', n: 'chart down decrease decline' },
      { c: '📋', n: 'clipboard list tasks todo' },
      { c: '📌', n: 'pin pushpin mark' },
      { c: '📎', n: 'paperclip attach' },
      { c: '✏️', n: 'pencil write edit' },
      { c: '📝', n: 'memo note write docs' },
      { c: '📚', n: 'books library learn read' },
      { c: '🔍', n: 'search magnify find look' },
      { c: '🔬', n: 'microscope research science lab' },
      { c: '🔭', n: 'telescope vision explore look' },
      { c: '🧪', n: 'test tube experiment lab chemistry' },
      { c: '🧬', n: 'dna genetics biology' },
      { c: '💡', n: 'idea lightbulb bright innovation' },
      { c: '🔧', n: 'wrench tool fix' },
      { c: '🔨', n: 'hammer build tool' },
      { c: '⚙️', n: 'gear settings cog config ops' },
      { c: '🛠️', n: 'tools build maintain' },
      { c: '🧰', n: 'toolbox tools kit' },
      { c: '🔑', n: 'key access auth unlock' },
      { c: '🔒', n: 'lock secure security private' },
      { c: '🛡️', n: 'shield security protect defense' },
      { c: '⚔️', n: 'swords battle fight versus' },
      { c: '🧲', n: 'magnet attract' },
      { c: '🔋', n: 'battery power energy' },
      { c: '🔌', n: 'plug power connect' },
      { c: '📡', n: 'antenna signal satellite broadcast' },
      { c: '⏰', n: 'alarm clock time' },
      { c: '⏳', n: 'hourglass time wait timer' },
      { c: '📅', n: 'calendar date schedule plan' },
      { c: '📷', n: 'camera photo picture' },
      { c: '🎥', n: 'video camera film record' },
      { c: '💰', n: 'money bag cash finance' },
      { c: '💎', n: 'diamond gem jewel premium' },
      { c: '🎁', n: 'gift present box' },
      { c: '🎈', n: 'balloon party' },
      { c: '🎉', n: 'party popper celebrate launch' },
      { c: '🪄', n: 'magic wand spell' },
      { c: '🔮', n: 'crystal ball future predict' },
      { c: '🪜', n: 'ladder climb step' },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    emojis: [
      { c: '❤️', n: 'red heart love' },
      { c: '🧡', n: 'orange heart' },
      { c: '💛', n: 'yellow heart' },
      { c: '💚', n: 'green heart' },
      { c: '💙', n: 'blue heart' },
      { c: '💜', n: 'purple heart' },
      { c: '🖤', n: 'black heart' },
      { c: '🤍', n: 'white heart' },
      { c: '💯', n: 'hundred perfect score full' },
      { c: '✅', n: 'check done yes complete tick' },
      { c: '❌', n: 'cross no wrong fail' },
      { c: '⚠️', n: 'warning caution alert' },
      { c: '❓', n: 'question help' },
      { c: '❗', n: 'exclamation important' },
      { c: '➕', n: 'plus add new' },
      { c: '♻️', n: 'recycle eco green loop' },
      { c: '⚛️', n: 'atom science physics react' },
      { c: '☯️', n: 'yin yang balance' },
      { c: '☮️', n: 'peace' },
      { c: '🆕', n: 'new badge' },
      { c: '🔝', n: 'top up best' },
      { c: '🚦', n: 'traffic light signal status' },
      { c: '🔴', n: 'red circle dot' },
      { c: '🟠', n: 'orange circle dot' },
      { c: '🟡', n: 'yellow circle dot' },
      { c: '🟢', n: 'green circle dot active' },
      { c: '🔵', n: 'blue circle dot' },
      { c: '🟣', n: 'purple circle dot' },
      { c: '🔶', n: 'orange diamond' },
      { c: '🔷', n: 'blue diamond' },
    ],
  },
]

/** Flat list of every catalog emoji. */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((cat) => cat.emojis)

/**
 * Filter the catalog by a free-text query, matching any keyword in each entry's
 * name (word-prefix or substring). Returns [] for an empty query.
 */
export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  return ALL_EMOJIS.filter((e) => e.n.includes(q))
}
