// ─── Template types (v2 — team marketplace) ──────────────────────────────────

export type TemplateSource = 'clawboo' | 'agency-agents' | 'awesome-openclaw'

export type AgentDomain =
  | 'academic'
  | 'design'
  | 'engineering'
  | 'game-development'
  | 'marketing'
  | 'paid-media'
  | 'product'
  | 'project-management'
  | 'sales'
  | 'spatial-computing'
  | 'specialized'
  | 'support'
  | 'testing'
  | 'openclaw'
  | 'clawboo'

/** First-class standalone agent entry in the agent catalog. */
export interface AgentCatalogEntry {
  /** Globally unique identifier, e.g. 'agency-frontend-developer' */
  id: string
  /** Display name shown on cards, e.g. 'Frontend Developer Boo' */
  name: string
  /** Short role label, e.g. 'Frontend Developer' */
  role: string
  emoji: string
  /** Hex accent color */
  color: string
  /** 1–2 sentence card description */
  description: string
  source: TemplateSource
  /** GitHub blob URL for MIT attribution */
  sourceUrl: string
  /** Source folder / domain */
  domain: AgentDomain
  /** Deeper sub-folder, e.g. 'unity' within game-development */
  subDomain?: string
  category: TemplateCategory
  tags: string[]
  /** Skill IDs from SKILL_CATALOG that this agent uses */
  skillIds: string[]

  /**
   * Distilled 20–40 line mission statement (written to SOUL.md on deploy).
   * Extracted from ## Core Mission, ## Critical Rules, ## Communication Style sections.
   */
  soulTemplate: string
  /**
   * FULL source .md content preserved verbatim (written to IDENTITY.md on deploy).
   * Zero-loss — must be the complete original file body.
   */
  identityTemplate: string
  /** TOOLS.md content built from skillIds (e.g. '# TOOLS\n\n## Skills\n- web-search') */
  toolsTemplate: string
  /** Optional AGENTS.md content when agent appears in a team with routing */
  agentsTemplate?: string
}

export type TemplateCategory =
  | 'engineering'
  | 'marketing'
  | 'sales'
  | 'product'
  | 'design'
  | 'testing'
  | 'content'
  | 'support'
  | 'education'
  | 'ops'
  | 'devops'
  | 'research'
  | 'game-dev'
  | 'spatial'
  | 'academic'
  | 'paid-media'
  | 'specialized'
  | 'general'

export interface AgentTemplate {
  name: string
  role: string
  soulTemplate: string
  identityTemplate: string
  toolsTemplate: string
  agentsTemplate?: string
}

export interface TeamTemplate {
  id: string
  name: string
  emoji: string
  color: string
  description: string
  category: TemplateCategory
  source: TemplateSource
  sourceUrl?: string
  tags: string[]
  /**
   * @deprecated Use `agentIds` referencing AGENT_CATALOG entries instead.
   * Kept for backward compatibility so hypothetical user-defined templates with
   * inline agents still typecheck. All first-party teams now use `agentIds`.
   */
  agents?: AgentTemplate[]
  /**
   * Agent IDs from AGENT_CATALOG. Replaces inline `agents` array.
   * When present, consumers should resolve via `resolveTeamAgents(team)`.
   */
  agentIds?: string[]
  /** Per-agent AGENTS.md routing content for this team, keyed by agentId */
  routing?: Record<string, string>
  /** Full workflow prose from source .md (e.g. awesome-openclaw usecase body) */
  workflowNarrative?: string
  /** true for domain-cluster synthetic "Excellence Teams" generated by ingestion script */
  isSynthetic?: boolean
}

/** Union of new TeamTemplate and legacy TeamProfile — used by CreateTeamModal and MarketplacePanel. */
export type ProfileLike = TeamTemplate | TeamProfile

// ─── Team profile types (legacy) ──────────────────────────────────────────────

/** @deprecated Use AgentTemplate instead. */
export interface AgentProfile {
  /** Display name — used as the agent's name on creation */
  name: string
  /** Raw content for the agent's SOUL.md file */
  soulTemplate: string
  /** Raw content for the agent's IDENTITY.md file */
  identityTemplate: string
}

/** @deprecated Use TeamTemplate instead. */
export interface TeamProfile {
  /** Unique identifier used for routing and keys */
  id: string
  /** Display name shown in the picker card */
  name: string
  /** Single emoji representing the team */
  emoji: string
  /** Accent color for the card (hex) */
  color: string
  /** One-sentence description shown on the card */
  description: string
  /** Ordered list of agents to create on deploy */
  agents: AgentProfile[]
  /** Skill identifiers to install in each agent's TOOLS.md */
  skills: string[]
  /** Preferred graph layout positions, indexed by agents array order */
  graphLayout: {
    positions: Array<{ x: number; y: number }>
  }
}
