// Guards on the COMMITTED catalog artifacts. These are what keep the 4.2 MB
// out of the tarball.
//
// `catalog/dist/` is generated by `pnpm catalog:build` and committed, which is
// what makes the fallback URL work with no infrastructure. Committed generated
// output only stays trustworthy if something proves it still matches its source,
// so that is what this file does: the index must be the packs' own listings, and
// each bundle's bytes must hash to the integrity the index publishes.
//
// The byte budget is the other half. Putting a body field back onto an index row
// pushes it past the ceiling immediately, so the budget fails long before anyone
// notices the browse payload grew.

import { createHash } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import {
  CATALOG_DIST,
  CATALOG_INDEX_FILE,
  assertCatalogEmitted,
} from '@/__vitest__/catalogFixtures'
import { SOURCE_AGENTS, SOURCE_PACKS, SOURCE_TEAMS } from '@/__vitest__/packSource'

import { BODY_FIELDS, CATALOG_SCHEMA_VERSION, type CatalogIndex } from '../catalogTypes'

/**
 * The browse payload ceiling. Today's index is ~79 KB across 141 entries
 * (~570 B per row). The headroom is deliberate: it absorbs real catalog growth
 * while still failing instantly if a body field is added back to a row.
 */
const INDEX_MAX_BYTES = 512 * 1024

assertCatalogEmitted()

const raw = fs.readFileSync(CATALOG_INDEX_FILE, 'utf8')
const index = JSON.parse(raw) as CatalogIndex & {
  packs: { publisher: string; slug: string; id: string; path: string; integrity: string }[]
}

interface Bundle {
  id: string
  version: string
  agents: { id: string; body: string }[]
  teams: { id: string; body: string }[]
  bodies: {
    agents: Record<string, { id: string; files: Record<string, string> }>
    teams: Record<string, { id: string }>
  }
}

function bundleFile(rowPath: string): string {
  // `path` is `<channel>/packs/...`; CATALOG_DIST already ends in the channel.
  return path.join(CATALOG_DIST, rowPath.replace(/^v1\//, ''))
}

describe('the committed browse index', () => {
  it('is readable by this build', () => {
    expect(index.schemaVersion).toBe(CATALOG_SCHEMA_VERSION)
  })

  it('has counts that match its own arrays', () => {
    expect(index.counts.agents).toBe(index.agents.length)
    expect(index.counts.teams).toBe(index.teams.length)
  })

  it('covers every entry in every pack', () => {
    expect(index.counts.agents).toBe(SOURCE_AGENTS.length)
    expect(index.counts.teams).toBe(SOURCE_TEAMS.length)
  })

  it(`stays under the ${INDEX_MAX_BYTES / 1024} KB browse budget`, () => {
    expect(
      Buffer.byteLength(raw),
      `index.json is ${Buffer.byteLength(raw)} B. If this jumped, a body field ` +
        `was probably added to an index row.`,
    ).toBeLessThan(INDEX_MAX_BYTES)
  })

  it('carries no body field on any row', () => {
    const leaked = new Set<string>()
    for (const row of [...index.agents, ...index.teams] as object[]) {
      for (const f of BODY_FIELDS) if (f in row) leaked.add(f)
    }
    expect([...leaked]).toEqual([])
  })

  // Canonical bytes, so the file is stable under a merge and a re-run: sorted
  // keys, no insignificant whitespace, and NO trailing newline. Those exact
  // bytes are what every published integrity value was computed over.
  it('is canonical bytes, not pretty-printed', () => {
    expect(raw.endsWith('\n'), 'a trailing newline would change every digest').toBe(false)
    expect(raw).not.toContain('\n  ')
  })

  it('matches the pack listings exactly, so the artifact cannot lag the source', () => {
    const drift: string[] = []
    for (const a of SOURCE_AGENTS) {
      const row = index.agents.find((r) => r.id === a.id)
      if (!row) {
        drift.push(`${a.id} is missing from the index`)
        continue
      }
      if (row.name !== a.name || row.role !== a.role || row.description !== a.description) {
        drift.push(`${a.id} card text disagrees with its listing`)
      }
    }
    for (const t of SOURCE_TEAMS) {
      const row = index.teams.find((r) => r.id === t.id)
      if (!row) {
        drift.push(`${t.id} is missing from the index`)
        continue
      }
      if (row.agentIds.join(',') !== t.members.map((m) => m.agentId).join(',')) {
        drift.push(`${t.id} roster disagrees with its listing`)
      }
    }
    expect(drift).toEqual([])
  })

  it('resolves every team member to an agent row', () => {
    const known = new Set(index.agents.map((a) => a.id))
    expect(index.teams.flatMap((t) => t.agentIds.filter((id) => !known.has(id)))).toEqual([])
  })

  it('names one pack row per pack in the tree', () => {
    expect(index.packs.map((p) => p.id).sort()).toEqual(
      SOURCE_PACKS.map((p) => p.manifest.id).sort(),
    )
  })
})

describe('the committed pack bundles', () => {
  it('exist, and their bytes hash to the integrity the index publishes', () => {
    const bad: string[] = []
    for (const row of index.packs) {
      const file = bundleFile(row.path)
      if (!fs.existsSync(file)) {
        bad.push(`${row.id}: ${row.path} is missing`)
        continue
      }
      const bytes = fs.readFileSync(file, 'utf8')
      const digest = `sha256-${createHash('sha256').update(bytes, 'utf8').digest('base64')}`
      if (digest !== row.integrity) bad.push(`${row.id}: ${digest} !== ${row.integrity}`)
    }
    expect(bad).toEqual([])
  })

  it('inline every body the pack declares, byte for byte', () => {
    const mismatched: string[] = []
    for (const row of index.packs) {
      const bundle = JSON.parse(fs.readFileSync(bundleFile(row.path), 'utf8')) as Bundle
      const pack = SOURCE_PACKS.find((p) => p.manifest.id === row.id)
      if (!pack) {
        mismatched.push(`${row.id} has no pack in the tree`)
        continue
      }
      for (const listing of pack.manifest.agents) {
        const onDisk = JSON.parse(fs.readFileSync(path.join(pack.dir, listing.body), 'utf8'))
        if (JSON.stringify(bundle.bodies.agents[listing.id]) !== JSON.stringify(onDisk)) {
          mismatched.push(`${row.id}/${listing.id}`)
        }
      }
      for (const listing of pack.manifest.teams) {
        const onDisk = JSON.parse(fs.readFileSync(path.join(pack.dir, listing.body), 'utf8'))
        if (JSON.stringify(bundle.bodies.teams[listing.id]) !== JSON.stringify(onDisk)) {
          mismatched.push(`${row.id}/${listing.id}`)
        }
      }
    }
    expect(mismatched).toEqual([])
  })

  it('preserves the zero-loss identity bodies', () => {
    const tooShort: string[] = []
    for (const row of index.packs) {
      const bundle = JSON.parse(fs.readFileSync(bundleFile(row.path), 'utf8')) as Bundle
      for (const [id, body] of Object.entries(bundle.bodies.agents)) {
        if ((body.files['IDENTITY.md'] ?? '').length < 500) tooShort.push(id)
      }
    }
    expect(tooShort).toEqual([])
  })

  // The filename-keyed map is the whole point of the body shape: adding a fifth
  // agent file must not be a schema change every reader has to follow.
  it('keys agent bodies by filename, not by a field name', () => {
    const bundle = JSON.parse(fs.readFileSync(bundleFile(index.packs[0]!.path), 'utf8')) as Bundle
    const first = Object.values(bundle.bodies.agents)[0]!
    for (const key of Object.keys(first.files)) {
      expect(key, `body key "${key}" is not a filename`).toMatch(/\.md$/)
    }
  })
})
